Cargo.lock, Cargo.toml, README.md, package.json, scripts/build.sh, scripts/epilogue.js, tests/asyncload.test.js, tests/attachment.test.js, tests/device.test.js, tests/encryption.test.js, tests/events.test.js, tests/helper.js, tests/identifiers.test.js, tests/machine.test.js, tests/requests.test.js, tests/sync_events.test.js, tests/tracing.test.js, tsconfig.json
Since we're moving everything around anyway, let's take the opportunity to rename the project to matrix-sdk-crypto-wasm to better distinguish it from matrix-sdk-crypto-nodejs.
=> Rename to matrix-sdk-crypto-wasm

.yarnrc, CHANGELOG.md, RELEASING.md, package.json
Ensure we have a relesed version of matrix-sdk-crypto-wasm to point to.
This also updates the format of the release branch and tag names to be more conventional.
=> Release v1.0.0

README.md
I've noticed a typo in an example of the `README.md`.
=> doc(readme): Fix typo in the example

src/identities.rs
`is_verified` is missing in `OwnUserIdentity`
Already implemented in `UserIdentity`
=> Add `is_verified` to `OwnUserIdentity`

CHANGELOG.md, src/backup.rs, src/machine.rs, tests/machine.test.js
Return an actual `BackupDecryptionKey` in tthe `BackupKeys` structure, rather than just the base64.
This is more symmetrical with `saveBackupDecryptionKey`, and also allows the public key to be extracted, which is useful sometimes.
=> Add `BackupKeys.decryptionKey`

src/future.rs
This patch implements `future_to_promise_with_custom_error`. It allows a `Future` to return a `JsValue` for the error, instead of returning a `JsError` directly. It provides more flexibility to return any kind of error types.
=> feat: Add `future_to_promise_with_custom_error`

src/error.rs, src/lib.rs, src/machine.rs, tests/machine.test.js
Fixes https://github.com/vector-im/crypto-internal/issues/145
Updated the `decrypt_room_event` API in order to add typed errors.
This level of details is needed by js-sdk/react-sdk, for requesting backup on UTDs as well as to report the type of errors to posthog.
Uses the new feature added here https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/22
=> Add detailed megolm decryption errors

Cargo.lock, Cargo.toml, src/machine.rs
Use the new `Store::identities_stream_raw` method introduced in https://github.com/matrix-org/matrix-rust-sdk/pull/2530 to avoid a resource leak.
=> Fix resource leak in `registerUserIdentityUpdatedCallback`

src/verification.rs
https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/verification/requests.rs#L395
`generate_qr_code` can return both a `QrVerification` or `None`
=> Fix doc of `verification.generate_qr_code` return

src/machine.rs
Adds support for secret stream in wasm.
=> basic callback on secret stream

CHANGELOG.md, Cargo.lock, Cargo.toml, src/identifiers.rs, src/machine.rs, tests/identifiers.test.js
Update rust sdk to revision https://github.com/matrix-org/matrix-rust-sdk/commit/c2bb76029ae6d99c741727e0f87abcd734377016
Including the fixes:
[Remove dashmap crate usage from matrix-sdk-crypto](https://github.com/matrix-org/matrix-rust-sdk/pull/2669)]
[Bugfix for invalidated private cross signing keys not being persisted](https://github.com/matrix-org/matrix-rust-sdk/pull/2676)
Some breaking changes:
Following API changes on [Ruma](https://github.com/ruma/ruma/commit/984cbda9629f50c9ce2614270630971c42749895): 
- Removed `localpart` and `server_name` method from `RoomId`.
Rust SDK:
OlmMachine.sign returns a Result now
=> Update rust sdk

CHANGELOG.md, Cargo.lock, Cargo.toml, src/tracing.rs
Rather than using a `Layer` which sends content to the JS console, construct an entire `Subscriber`, which allows us better control over what format is used, and includes data attached to spans.
=> Rewrite Tracing module

CHANGELOG.md, src/requests.rs, src/responses.rs, tests/machine.test.js
Fixes https://github.com/vector-im/element-web/issues/26382
When used in WebR, `olmMachine.shareRoomKey()` was always returning ToDeviceRequest without id (`undefined`).
As a consequence markRequestAsSent was never called, and room keys were re-shared for each message.
I tried to clarify in bindings when there should be a `request_id`. So I replaced a most of the `pub id: Option<JsString>,` with `pub id: JsString,`.
The conversion methods have been updated also.
=> Fix ToDeviceRequest conversion

CHANGELOG.md, Cargo.lock, Cargo.toml, build.rs, src/lib.rs, tests/machine.test.js
Add more informations to the `getVersions()` API:
- The git sha of the binding crate (e.g `e252b3c`)
- The git description of the binding crate (e.g `v2.1.1`)
Using the same method [used for ffi bindings](https://github.com/matrix-org/matrix-rust-sdk/commit/1510576ce1b8312fd972c4563ead46242887cb18)
=> Add git sha/description to version

CHANGELOG.md, Cargo.lock, Cargo.toml, src/machine.rs, src/requests.rs, tests/helper.js
`bootstrapCrossSigning` now returns its own type, which can contain two or three nested requests. Create a new response type wrapper and return it.
Some other cleanups while we are here:
* Get rid of `OutgoingRequests` wrapper, which was more confusing than helpful.
* Rename `SigningKeysUploadRequest` to `UploadSigningKeysRequest` for consistency with matrix-rust-sdk.
=> Update rust-sdk ver and `bootstrapCrossSigning` response

CHANGELOG.md, Cargo.lock, Cargo.toml, src/machine.rs
Changes required:
* Remove backups_v1 feature flag (cf https://github.com/matrix-org/matrix-rust-sdk/pull/2813)
* Changed API of `encrypt_room_event_raw` (cf https://github.com/matrix-org/matrix-rust-sdk/pull/2798)
* Use new `import_exported_room_keys` for key import (cf https://github.com/matrix-org/matrix-rust-sdk/pull/2759). We actually need to fix this properly and expose a separate method for importing backups (cf https://github.com/vector-im/element-web/issues/26347), but that will be a separate PR.
=> Update to latest version of Matrix Rust SDK

CHANGELOG.md, src/machine.rs, src/types.rs, tests/machine.test.js
Exposes the new import methods added in https://github.com/matrix-org/matrix-rust-sdk/pull/2759. Also adds a new return type which doesn't rely quite so much on JSON-encoded objects.
The old method is deprecated.
~~This PR currently based on #53.~~
=> Expose new methods for importing room keys

src/machine.rs
I need this for a workaround for https://github.com/matrix-org/matrix-rust-sdk/issues/2896.
=> Add `timeout` param to `get_device` and `get_user_devices`

CHANGELOG.md, Cargo.toml, scripts/build.sh
In order to help debugging/profiling, it's useful to include the names of the Rust symbols in the generated wasm.
It does increase the wasm from 4.3M to 5.4M (and hence the js module which includes the base64-ed wasm from ~6M to 7.3M) ... but I guess we have to live with that.
There are a couple of commits here. The second isn't strictly related but is a quick cleanup while I was in the area.
=> Include debug symbols in wasm output

Cargo.lock
This provides these changes from matrix-rust-sdk (edited for brevity):
- 92212cc32843b4 Clarify the meaning of the sessions field in PendingBackup
- 6ffb0181e46f2d Make sure qrcode feature is additive
- 614bf942c082cf build(deps): bump zerocopy from 0.7.26 to 0.7.31
- 512509ce8be9ec Switch to using chunk_large_query_over in mark_inbound_group_sessions_as_backed_up
- 5310f41cdacf68 integration-testing: Add test for QR verification
- 326935db637fe3 feat(base): Correct implementations for `MemoryStore` media removal.
- 416bc8b0e4de2e feat(base): Implement `Media::uri`.
- edd113a17c9276 feat(common): Implement `RingBuffer::remove`.
- a3aa55ce91e159 Use the limit() method to find the variable limit
- c5b11fc2f89ee0 feat(sdk): Simplify code from `Media::get_media_content`.
- e2ea19ee770520 Add …
=> Bump dependency versions, including matrix-rust-sdk

CHANGELOG.md, src/machine.rs, src/store.rs, tests/machine.test.ts
A prerequisite for supporting migration from libolm: opening the indexeddb takes a long time, so we don't want to do it for each step in the migration.
=> Create new `StoreHandle` class to save repeatedly opening stores

CHANGELOG.md, src/machine.rs, tests/machine.test.ts
Counts the invalid keys from backup and reports them to the callback, rather than returning an error immediately and stopping import.  Works with JS-SDK PR https://github.com/matrix-org/matrix-js-sdk/pull/4006
Fixes https://github.com/element-hq/element-web/issues/26774
=> don't die when we have invalid keys in backup

Cargo.lock, Cargo.toml
... and disable the state store in `matrix-sdk-indexeddb`. We don't use the state store, so can save some build time by excluding it (since this also means we no longer pull in `matrix-sdk-base`).
=> Update matrix-rust-sdk version

CHANGELOG.md, src/libolm_migration.rs
Empirically, some sessions in the legacy store lack a `keysClaimed` property. In order to accommodate such sessions in the import, we make the property optional.
=> libolm_migration: make `sender_signing_key` optional

src/device.rs, src/identities.rs, src/libolm_migration.rs, src/machine.rs, src/verification.rs
#82 updated the documentation on some of the exported methods. This PR cleans up a few bits. Principally: `VerificationMethod` is an int, so there is no "owner", and it is not invalidated by passing it into a Rust method.
=> Update documentation added in #82

CHANGELOG.md, Cargo.lock, src/machine.rs, src/types.rs, tests/machine.test.ts
Part of https://github.com/element-hq/element-web/issues/26108
=> Support for saving and loading room settings

CHANGELOG.md, src/encryption.rs
Related: https://github.com/element-hq/element-web/issues/26610, which will be fixed by this once matrix-js-sdk is updated
=> add unknown to EncryptionAlgorithm enum

Cargo.lock, package.json
Update dependencies, including matrix-rust-sdk to 5957d9603bd8a3f00ddd9a52bda80224c853bcd1 to get https://github.com/matrix-org/matrix-rust-sdk/pull/3095 which speeds up the schema upgrade v8->v10 again. See https://github.com/element-hq/element-web/issues/26948
=> Release 4.5.0

Cargo.lock, src/machine.rs
For Store::export_room_keys_stream.
Code updated to accommodate the move of `export_room_keys` into `Store`, and the rename of `OlmMachine::invalidate_group_session` to `OlmMachine::discard_room_key`.
(Also update the general dependencies.)
=> Update matrix-sdk to dcf00697539321cf4eac5cd4929d45347b947da7

Cargo.lock, Cargo.toml, src/machine.rs
Applies on top of https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/106
Make use of the new `export_room_keys_stream` method from https://github.com/matrix-org/matrix-rust-sdk/pull/3144 to avoid one copy of the keys in the export process, by directly serialising to a JSON string, without taking the intermediate step into a `Vec<ExportedRoomKey>`.
Part of https://github.com/element-hq/element-web/issues/26681
=> Use export_room_keys_stream to reduce export memory usage

CHANGELOG.md, package.json, scripts/build.sh, tests/asyncload.test.js, tests/attachment.test.js, tests/backup.test.js, tests/device.test.js, tests/encryption.test.js, tests/events.test.js, tests/helper.js, tests/identifiers.test.js, tests/machine.test.ts, tests/requests.test.js, tests/sync_events.test.js, tests/tracing.test.js
This solves a problem with the webpack-dev-server, which would see the half-built javascript output and explode with a big error about not supporting `require("path")`.
=> Give final build output a new name

CHANGELOG.md, Cargo.lock, src/dehydrated_devices.rs, src/device.rs, src/lib.rs, src/libolm_migration.rs, src/machine.rs, src/requests.rs, tests/dehydrated_devices.test.js, tests/dehydrated_devices.test.ts
Depends on https://github.com/matrix-org/matrix-rust-sdk/pull/3164
=> Add bindings for dehydrated devices

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib.rs, src/machine.rs, src/qr_login.rs, src/store.rs, src/vodozemac/ecies.rs, src/vodozemac/mod.rs, tests/ecies.test.ts, tests/qr_code.test.js
This PR depends on #116  and #117 so opening it as a draft. It adds all the functionality necessary to make QR code login work in the js-sdk.
A review commit by commit is recommended.
=> Expose QR login related structs and methods

CHANGELOG.md, Cargo.lock, src/store.rs, tests/machine.test.ts
... allowing the application to pass in the key directly if they have a cryptographically-secure key.
Part of https://github.com/element-hq/element-web/issues/26821. Requires https://github.com/matrix-org/matrix-rust-sdk/pull/3423 (so will fail CI for now)
=> Expose new method `OlmMachine.openWithKey`

CHANGELOG.md, Cargo.lock, src/machine.rs, tests/machine.test.ts
Bump to a version of the rust SDK that includes https://github.com/matrix-org/matrix-rust-sdk/pull/3448 and https://github.com/matrix-org/matrix-rust-sdk/pull/3456, to fix https://github.com/matrix-org/matrix-rust-sdk/issues/3447.
Also, pass the backup version into `import_backed_up_room_keys` to avoid using the deprecated method on `BackupMachine`.
=> Fix backed-up keys being re-backed-up

CHANGELOG.md, package.json
I've changed the interface of `OlmMachine.importBackedUpRoomKeys`, so this is a breaking change, hence the major version bump
=> Prepare release of v5.0.0

CHANGELOG.md, src/machine.rs
=> Improve types and docs of `{import,export}SecretsBundle`

CHANGELOG.md, package.json
A bunch of methods were renamed and converted to non-async methods, which requires us to do a major bump.
=> Prepare release of v6.0.0

CHANGELOG.md, src/libolm_migration.rs, tests/libolm_migration.test.ts
Fixes: https://github.com/element-hq/element-web/issues/27590
=> Set creation time of OlmDevices migrated from legacy to zero

src/device.rs
In cbd7ca9d4 the Device.verificationRequest method was converted from an async method to a sync one, this was done because the underlying SDK method has received the same treatment.
The doc comment was not updated to reflect this change and claimed that it's still returning a promise. This patch fixes this mistake.
Closes: https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/127
=> Fix a doc comment incorrectly stating that the function returns a promise

CHANGELOG.md, Cargo.lock, src/encryption.rs, src/error.rs, src/identities.rs, src/machine.rs, tests/dehydrated_devices.test.ts, tests/encryption.test.js, tests/machine.test.ts
changes:
- add support for `ShieldStateCode` (ref: matrix-org/matrix-rust-sdk#3786)
- add `error_on_verified_user_problem` field in device-based strategy (ref: matrix-org/matrix-rust-sdk#3810)
- since the device-based strategy was getting more complicated with new fields, I opted to change the JavaScript interface so that it's more structured, rather than trying to throw new variants into the enum to cover all the options
- add decryption settings for checking sender device trust (ref: matrix-org/matrix-rust-sdk#3899)
- expose the functions for handling identity pinning and previously-verified users (ref: matrix-org/matrix-rust-sdk#3846, matrix-org/matrix-rust-sdk#3795, matrix-org/matrix-rust-sdk#2629)
=> Update to latest Rust SDK

CHANGELOG.md, src/error.rs
Apps need to distinguish between the different reasons for the sender not being trusted, so they can show the right error message to the user.
=> Return finer-grained errors for sender-not-trusted

CHANGELOG.md, Cargo.lock, src/machine.rs, tests/machine.test.ts
This is required for SSS in Element-Web. See https://github.com/matrix-org/matrix-rust-sdk/pull/3965 for more info.
Had to run `cargo update matrix-sdk-crypto` to pull in the latest code with this function. Hopefully I've done it right.
=> Add mark_all_tracked_users_as_dirty

CHANGELOG.md, Cargo.lock, src/error.rs, src/identities.rs, src/machine.rs, tests/machine.test.ts
In my quest to make method names consistent I first needed to reflect previous changes from matrix-sdk.
=> Bring up-to-date with latest matrix-sdk (5d46b35d)

CHANGELOG.md, Cargo.lock, package.json, src/verification.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/158
=> Update matrix-sdk + others, release v10.1.0

CHANGELOG.md, Cargo.lock, src/identifiers.rs, src/machine.rs, src/requests.rs, tests/identifiers.test.js
Fixes https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/162
Note: the individual commits don't actually compile. I found it helpful to separate them out to get my head around the changes, but if we want a clean commit history that always compiles, we should squash them. I actually prefer to keep them separate in this case, but I am persuadable.
=> Update matrix-sdk dependency to 75683d268fc2e

.github/latest_matrix_sdk_failed_issue_template.md
Fixes https://github.com/element-hq/crypto-internal/issues/391
=> Issue template for latest matrix-sdk failure mentions git cliff instead of CHANGELOG

package.json, tests/asyncload.test.js, tests/attachment.test.js, tests/backup.test.js, tests/dehydrated_devices.test.ts, tests/device.test.js, tests/ecies.test.ts, tests/encryption.test.js, tests/events.test.js, tests/helper.js, tests/identifiers.test.js, tests/libolm_migration.test.ts, tests/machine.test.ts, tests/qr_code.test.js, tests/requests.test.js, tests/sync_events.test.js, tests/tracing.test.js, tests/vodozemac_types.test.ts, tsconfig.json, yarn.lock
Groundwork for https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/167.
=> Update tests to use the public entry point to the module

Cargo.toml
This is significantly more expensive at compilation time, but shrinks the size of the WASM file from 6MB to 5MB (2.6MB to 1.8MB compressed).
=> Further shrink the WASM output by using more aggressive optimizations

CHANGELOG.md, scripts/build.sh
This solves a problem, introduced in #167, with the webpack-dev-server, which would see the half-built javascript output and explode with a big error about `Can't resolve './pkg/matrix_sdk_crypto_wasm_bg.js'`
(See also #109, where a similar problem was fixed before.)
=> Stop deleting build results during rebuilds

CHANGELOG.md, index.js, index.mjs, node.js, node.mjs
This fixes a problem (introduced in #167) on Chrome, which would complain about the module being too big. It also significantly simplifies the code on the browser entry points, because `instantiateStreaming` is widely supported.
=> Use asynchronous wasm instantiation methods where possible

Cargo.toml
Since https://github.com/rust-lang/rust/pull/132577 (currently in rust nightly), we get hundreds of lint warnings:
```
warning: unexpected `cfg` condition name: `wasm_bindgen_unstable_test_coverage`
--> src/rust/lib.rs:83:1
|
83 | #[wasm_bindgen(start)]
```
The correct solution is to upgrade wasm-bindgen, but legend has it that is difficult. For now, let's silence the lint.
=> Silence annoying lint warning

README.md, index-wasm-esm.mjs, index.mjs, package.json
Some environments support loading WASM modules directly as ESM, and that gives better results than the existing entry points. For example, Webpack is able to include it inside the same bundle as the rest of the sources.
=> Add another entrypoint using wasm-as-esm support

Cargo.lock, Cargo.toml
This undoes the change made in 0378300821d2aeca7d2f184141c864f2fc189051, except it stays on the same commit SHA of matrix-rust-sdk, but changes the branch specifier.
We temporarily switched to the branch `release-for-crypto-wasm-12` of `matrix-rust-sdk` to release 12.1.0 without needing to fix the other things needing work to get the latest `matrix-rust-sdk`. This change puts us back onto the main branch, as normal.
=> Go back to depending on matrix-rust-sdk main branch

package.json, src/libolm_migration.rs, src/machine.rs
```
/opt/homebrew/bin/yarn run doc
yarn run v1.22.22
$ typedoc --tsconfig .
[warning] Failed to resolve link to "#migrateBaseData" in comment for BaseMigrationData
[warning] Failed to resolve link to "#migrateOlmSessions" in comment for Migration.migrateBaseData
[warning] Failed to resolve link to "#migrateMegolmSessions" in comment for Migration.migrateBaseData
[warning] Failed to resolve link to "#migrateBaseData" in comment for Migration.migrateOlmSessions
[warning] Failed to resolve link to "#migrateBaseData" in comment for Migration.migrateMegolmSessions
[warning] Failed to resolve link to "BackupMachine" in comment for OlmMachine.importSecretsBundle
[warning] Failed to resolve link to "identities.OwnUserIdentity" in comment for OlmMachine.getIdentity
[warning] Failed to resolve link …
```
=> Fix typedoc warnings

src/machine.rs, tests/machine.test.ts
Modern wasm_bindgen allows us just to write `async` functions, which is much more idiomatic, and gives better typescript types in the generated output.
=> Remove uses of `future_to_promise` in `machine.rs`

index.d.ts
https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/201 introduced some build errors (and I forgot to check the CI afterwards). [Specifically](https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/actions/runs/13261441394):
```
Module '"@matrix-org/matrix-sdk-crypto-wasm"' has no exported member 'DehydratedDeviceKey'.
```
... and similar.
The problem turns out to be that, given *certain* settings for tsc, it refuses to consider relative imports with no filename extension, and silently ignores the import. Yay.
Here is another go at fixing the import situation.
(Have I ever mentioned how much I hate the JS ecosystem? HOW CAN THIS BE SO HARD?)
=> Fix tsc errors

CHANGELOG.md, src/machine.rs, tests/machine.test.ts
This reverts commit eea167e45470cfa387a89ea5b4b04e2a579891b5.
Unfortunately, most of this change is unsound.
With an explicit `future_to_promise`, we are able to clone the underlying `matrix_sdk_crypto::OlmMachine` (and its constituent `Arc`) *before* returning a Promise to the javascript, meaning even if the wrapping `matrix_sdk_crypto_wasm::OlmMachine` is dropped, the underlying `OlmMachine` hangs around.
An `async` function does nothing until it is polled, meaning there is plenty of time for the Javascript to get hold of the Promise and drop its reference to the OlmMachine, before we try and clone it. It's fine (I think) if we let the Javascript finalizer manage cleanup; but we deliberately drop OlmMachine, in an attempt to get it to close its indexeddb connection.
I'd go so far as to …
=> Revert "Remove uses of `future_to_promise` in `machine.rs` (#193)"

tests/machine.test.ts
Some history:
* #193 introduced some improvements to the generated typescript types. As part  of that PR, we had to add a few assertions in `machine.test.ts` to handle `undefined` values.
* #205 reverted that change, including the improvements in `machine.test.ts`. (I should probably not have reverted the fixes to `machine.test.ts`: they were correct, even though they were no longer *required* after reverting the types.)
* #206 manually reintroduced the type improvements, but I forgot about the fixes to `machine.test.ts`.
So this commit finally reintroduces those improvements to `machine.test.ts`.
=> Reinstate type fixes in `machine.test.ts` from #193

Cargo.toml
The default_features directive in the Cargo.toml file has been replaced by default-features.
This is shown as a warning currently but if we switch to Rust 2024 it will become an error, so let's just use the new variant.
=> Silence a cargo warning about default_features

.github/workflows/ci.yml, .github/workflows/netlify.yaml
An attempt to upload our documentation to Netlify, to make it easier to review. This is mostly cargo-culted from the js-sdk's implementation of the same.
Part of https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/181.
=> Deploy documentation previews to github actions

CHANGELOG.md, src/vodozemac/mod.rs, src/vodozemac/pk_encryption.rs, tests/pk_encryption.test.ts
Not much to say here. I split this a bit up so it might be easier to review commit by commit. All in all, it's pretty boring.
I wasn't sure if we need to support to encrypt/decrypt bytes as well as strings so we have support for both.
=> Expose the `PkEncryption` support from vodozemac

Cargo.lock
The latest ulid version requries getrandom 0.3, which needs more changes: https://docs.rs/getrandom/#webassembly-support
=> Bump Rust dependencies except ulid

.cargo/config.toml, Cargo.lock, Cargo.toml, build.rs
Update all of our dependencies, other than matrix-rust-sdk.
Updating `ulid` and `vergen` is not completely trivial, so they are pulled out to separate commits.
There was previously a problem with serde-wasm-bindgen (https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/161), but it seems that has been fixed.
=> Update dependencies, other than matrix-rust-sdk

src/machine.rs
Would have helped when debugging https://github.com/element-hq/element-web/issues/29878
Errors like this were made non-fatal in https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/85 but here we make them a little more visible.
Please review this carefully as I don't have any way to write tests for this code (right?).
=> Log warnings when we fail to parse a backed-up room key

.github/workflows/latest-matrix-sdk-crypto.yml
We need to make sure we're not pinned to a release before attempting to upgrade.
=> Fix nightly github workflow to build against latest matrix-sdk

CHANGELOG.md, Cargo.lock, Cargo.toml, index.d.ts, src/machine.rs, src/types.rs, tests/helper.js, tests/machine.test.ts
Bump the dependency om matrix-rust-sdk to `59ecb1edb`, which includes https://github.com/matrix-org/matrix-rust-sdk/pull/4935, which modifies `receive_sync_changes` so that it returns an list of `ProcessedToDeviceEvent` enums instead of `Raw<AnyToDeiceEvent>`s.
To reflect this in javascript, we define a new wrapper struct for each variant, which can then be duck-typed. This is the same trick we use with the request objects returned by `outgoingRequests`.
This is the first of several PRs that I am pulling out of https://github.com/matrix-org/matrix-sdk-crypto-wasm/pull/226.
=> Return an array of `ProcessedToDeviceEvent` from `receiveSyncChanges`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/requests.rs, src/responses.rs, src/verification.rs
Update the wasm bindings as far as https://github.com/matrix-org/matrix-rust-sdk/commit/022068996.
The breaking changes here are https://github.com/matrix-org/matrix-rust-sdk/pull/5048 and https://github.com/matrix-org/matrix-rust-sdk/pull/5134, which wrap things in `Box` or `Arc`. Review commit-by-commit.
The second of several PRs that I am pulling out of #226.
=> Bump sdk to 022068996

CHANGELOG.md, Cargo.lock, Cargo.toml, src/machine.rs, src/responses.rs, src/types.rs, tests/machine.test.ts
Bump SDK to https://github.com/matrix-org/matrix-rust-sdk/commit/0f73ffde, which exposes encryption info on to-device events.
We add a new `ToDeviceEncryptionInfo` struct, which is a member of  `DecryptedToDeviceEvent`.
Review commit-by-commit.
Based on https://github.com/matrix-org/matrix-sdk-crypto-wasm/pull/238.
The third of several PRs that I am pulling out of #226.
=> Expose EncryptionInfo on decrypted to-device events

CHANGELOG.md, Cargo.lock, Cargo.toml, src/backup.rs, src/dehydrated_devices.rs, src/error.rs, src/libolm_migration.rs, src/machine.rs, src/store.rs, src/types.rs
Update the SDK to  https://github.com/matrix-org/matrix-rust-sdk/commit/6ab11a032, which includes matrix-org/matrix-rust-sdk#5219, which adds a new `VerificationLevel` for mismatched senders. We expose this to the application via a new `DecryptionErrorCode`.
=> Add `DecryptionErrorCode::MismatchedSender`.

CHANGELOG.md, src/machine.rs, src/types.rs, tests/device.test.js, tests/helper.ts, tests/shared_room_history.test.ts, tsconfig.json
Expose the new [MSC4268](https://github.com/element-hq/element-meta/issues/2872) support that was added in matrix-sdk-crypto v0.12.0 (and gained indexeddb support in matrix-sdk-indexeddb v0.13.0).
Part of https://github.com/element-hq/element-meta/issues/2871.
=> Expose functionality for encrypted history sharing

CHANGELOG.md, Cargo.lock, Cargo.toml, src/encryption.rs, src/machine.rs, src/types.rs, tests/encryption.test.ts, tests/machine.test.ts
Introduces support for experimental state event encryption, mostly conforming to https://github.com/matrix-org/matrix-rust-sdk/issues/5397. Features are **NOT** locked behind any feature flags, but this should not cause issues as we use `Self::default()` in the marked constructor.
- Adds `OlmMachine.encryptStateEvent`;
- Adds `EncryptionSettings.encryptStateEvents`.
- Adds `RoomSettings.encryptStateEvents`
=> feat: Add experimental encrypted state event support.
