.github/workflows/ci.yml
Documentation: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
=> ci: Fix git ref comparison

.github/workflows/release.yml
… now that the bindings package is at the repo root.
=> ci: Remove PKG_PATH references

.github/workflows/release.yml, CHANGELOG.md, package.json
=> Release v1.0.1

CHANGELOG.md, Cargo.lock, Cargo.toml, package.json
Prepare a new release so we can start building on it in the js-sdk
=> matrix-sdk-crypto-wasm v1.1.0

Cargo.lock, Cargo.toml, src/machine.rs
Followup on https://github.com/matrix-org/matrix-rust-sdk/pull/2318
=> backups: expect a KeysBackupRequest

CHANGELOG.md, src/types.rs
=> Expose `SignatureVerification.trusted`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/machine.rs, tests/machine.test.js
Expose the new stream added in ~~https://github.com/matrix-org/matrix-rust-sdk/pull/2516~~ https://github.com/matrix-org/matrix-rust-sdk/pull/2373
Part of https://github.com/vector-im/crypto-internal/issues/148
=> Add `OlmMachine.registerUserIdentityCallback`

src/machine.rs
Analogous to https://github.com/matrix-org/matrix-rust-sdk-crypto-nodejs/pull/7#discussion_r1280379537
=> Document the reset arg of bootstrap_cross_signing

CHANGELOG.md, Cargo.lock, Cargo.toml, tests/machine.test.js
Part of https://github.com/vector-im/element-web/issues/25722
=> Enable message-ids on to-device messages

package.json, yarn.lock
0.10.x is pretty old now. Time for an upgrade.
=> Upgrade wasm-pack

.cargo/config, CHANGELOG.md, Cargo.lock, src/machine.rs, tests/machine.test.js
Follow-up to https://github.com/matrix-org/matrix-rust-sdk/pull/2902. Required for https://github.com/vector-im/element-web/issues/26524.
=> New accessors `roomKeyRequestsEnabled` and `roomKeyForwardingEnabled`

src/machine.rs
See ffi documentation here https://github.com/matrix-org/matrix-rust-sdk/blob/e652069896377a2c11318a036f24c461a5054d20/bindings/matrix-sdk-crypto-ffi/src/machine.rs#L753
=> Update docs regarding locks to be consistent with ffi docs

CHANGELOG.md, src/machine.rs, tests/machine.test.ts
down with snake_case, long live camelCase
=> Fix jsName for `OlmMachine::init_from_store`

CHANGELOG.md
PR #72 landed in 4.0.1, not 4.0.0.
=> Fix changelog for 4.0.1

RELEASING.md
Minor clarifications to `RELEASING.md`.
=> Clarify release process

README.md
From my phone when looking at the README quickly. I think the fix is correct.
=> doc: Fix example

CHANGELOG.md
I forgot to `git add` :facepalm:
=> Add missing changelog entry for 4.5.0

CHANGELOG.md, Cargo.lock, src/machine.rs, tests/machine.test.ts
Followup on https://github.com/matrix-org/matrix-rust-sdk/pull/3275
=> Add new accessor `OlmMachine.deviceCreationTimeMs`

tests/qr_code.test.js
=> QR spelling

Cargo.lock, src/responses.rs
and fix our use of TimelineEvent, which has changed shape.
=> Update matrix-sdk to 3558886b98992

CHANGELOG.md, Cargo.lock, package.json, src/identifiers.rs
Applies after https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/164
Fixes https://github.com/element-hq/crypto-internal/issues/390
Fixes https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/163
=> Release v11.0.0

CHANGELOG.md, package.json
Adds support for dehydration key caching.
=> Release v13.0.0

CHANGELOG.md, Cargo.lock, src/encryption.rs, tests/encryption.test.ts
`cargo update`, which brings in https://github.com/matrix-org/matrix-rust-sdk/pull/4581.
Fixes: https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/180
=> Update dependency versions

README.md
=> README: fix broken link to documentation

.prettierignore, CHANGELOG.md, Cargo.lock, Cargo.toml
We're finally ready to upgrade!
=> Bump Rust SDK to 0.12.0

CHANGELOG.md, Cargo.lock, Cargo.toml, package.json
... including pinning the rust SDK to a release version
=> Prepare release v15.1.0

CHANGELOG.md, Cargo.toml, index.d.ts, src/dehydrated_devices.rs, src/machine.rs, src/requests.rs, src/types.rs, tests/machine.test.ts
Fixes https://github.com/matrix-org/matrix-sdk-crypto-wasm/issues/254
=> update to git version of Rust crypto SDK (2025-07-30)

Cargo.lock, src/machine.rs, src/types.rs, tests/machine.test.ts
Fixes https://github.com/matrix-org/matrix-sdk-crypto-wasm/issues/258
=> Update to Rust crypto SDK 2025-08-15
